'use client';

import { SessionProvider } from 'next-auth/react';
import type { Session } from 'next-auth';

import FlashLight from '../components/common/FlashLight';
import Header from '../components/layout/header/Header';

import '../globals.sass';
import styles from './RootLayout.module.sass';

import type { FC } from 'react';
// import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }
type Props = {
  children: React.ReactNode;
  params: {
    session: Session;
  };
};

const RootLayout: FC<Props> = ({
  children,
  params: { session, ...params },
}) => {
  return (
    <html lang="en">
      <SessionProvider session={session}>
        <body>
          <div className={styles.flashlightWrapper}>
            <div className={styles.main_wrapper}>
              <Header />
              {children}
              <FlashLight />
            </div>
          </div>
        </body>
      </SessionProvider>
    </html>
  );
};

export default RootLayout;
